[build]
  publish = "dist/public"
  functions = "netlify/functions"
  command = "npm install --include=dev && npm run build"

[functions]
  external_node_modules = ["express", "drizzle-orm", "@neondatabase/serverless", "tsx"]
  # Include environment variables for functions
  included_files = ["shared/**"]

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev:netlify"
  targetPort = 8888
  port = 8888
  publish = "dist/public"
  autoLaunch = false